import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

// import { useNetwork } from "wagmi";

import { Button } from "@/components/elements";

const Landing: NextPage = () => {
  const router = useRouter();

  // const [{ data: networkData }, switchNetwork] = useNetwork();

  return (
    <div className={``}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={``}>
        <Button onClick={() => router.push(`/daos`)}>DAOs Page</Button>
      </main>
      <footer className={``}></footer>
    </div>
  );
};

export default Landing;
