import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { useNetwork } from "wagmi";

import { Button } from "@/components/elements";

const Landing: NextPage = () => {
  const router = useRouter();

  const [{ data: networkData }, switchNetwork] = useNetwork();

  if (!process.env.NODE_ENV || process.env.NODE_ENV === "development") {
    console.log("development");
  } else {
    console.log("production");
  }

  return (
    <div className={``}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={``}>
        <div>
          <Button onClick={() => router.push(`/daos`)}>DAOs Page</Button>
        </div>
      </main>

      <footer className={``}></footer>
    </div>
  );
};

export default Landing;
